In [2]:
import os
import pandas as pd
from sklearn.model_selection import KFold, StratifiedKFold

In [3]:
image_sizes = [128, 128, 128]

data_dir = "/Volumes/Data/kaggle/raw"

In [16]:
df_train: pd.DataFrame = pd.read_csv(os.path.join(data_dir, 'train.csv'))
mask_files: list = os.listdir(f'{data_dir}/segmentations')
df_mask: pd.DataFrame = pd.DataFrame({
    'mask_file': mask_files,
})
df_mask['StudyInstanceUID'] = df_mask['mask_file'].apply(
  lambda x: x[:-4]
)
df_mask['mask_file'] = df_mask['mask_file'].apply(
  lambda x: os.path.join(data_dir, 'segmentations', x)
)
df = df_train.merge(df_mask, on='StudyInstanceUID', how='left')
df['image_folder'] = df['StudyInstanceUID'].apply(
  lambda x: os.path.join(data_dir, 'train_images', x)
)
df_seg = df[df["mask_file"].notna()].reset_index(drop=True)

kf: KFold = KFold(5)
df_seg['fold'] = -1
for fold, (train_idx, validation_idx) in enumerate(kf.split(df_seg, df_seg)):
  df_seg.loc[validation_idx, 'fold'] = fold

display(df_train)
display(df_mask)
display(df)
display(df_seg)

               StudyInstanceUID  patient_overall  C1  C2  C3  C4  C5  C6  C7
0      1.2.826.0.1.3680043.6200                1   1   1   0   0   0   0   0
1     1.2.826.0.1.3680043.27262                1   0   1   0   0   0   0   0
2     1.2.826.0.1.3680043.21561                1   0   1   0   0   0   0   0
3     1.2.826.0.1.3680043.12351                0   0   0   0   0   0   0   0
4      1.2.826.0.1.3680043.1363                1   0   0   0   0   1   0   0
...                         ...              ...  ..  ..  ..  ..  ..  ..  ..
2014  1.2.826.0.1.3680043.21684                1   0   1   0   0   0   1   1
2015   1.2.826.0.1.3680043.4786                1   0   0   0   0   0   0   1
2016  1.2.826.0.1.3680043.14341                0   0   0   0   0   0   0   0
2017  1.2.826.0.1.3680043.12053                0   0   0   0   0   0   0   0
2018  1.2.826.0.1.3680043.18786                1   0   0   0   0   0   0   1

[2019 rows x 9 columns]

,mask_file,StudyInstanceUID
0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.2243
1,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.3376
2,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.18906
3,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.18480
4,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.30640
...,...,...
82,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.24606
83,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.8574
84,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.27292
85,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.6376
86,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,1.2.826.0.1.3680043.26990

,StudyInstanceUID,patient_overall,C1,C2,C3,C4,C5,C6,C7,mask_file,image_folder
0,1.2.826.0.1.3680043.6200,1,1,1,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
1,1.2.826.0.1.3680043.27262,1,0,1,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
2,1.2.826.0.1.3680043.21561,1,0,1,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
3,1.2.826.0.1.3680043.12351,0,0,0,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
4,1.2.826.0.1.3680043.1363,1,0,0,0,0,1,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....
...,...,...,...,...,...,...,...,...,...,...,...
2014,1.2.826.0.1.3680043.21684,1,0,1,0,0,0,1,1,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
2015,1.2.826.0.1.3680043.4786,1,0,0,0,0,0,0,1,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
2016,1.2.826.0.1.3680043.14341,0,0,0,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
2017,1.2.826.0.1.3680043.12053,0,0,0,0,0,0,0,0,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....
2018,1.2.826.0.1.3680043.18786,1,0,0,0,0,0,0,1,NaN,/Volumes/Data/kaggle/raw/train_images/1.2.826....

,StudyInstanceUID,patient_overall,C1,C2,C3,C4,C5,C6,C7,mask_file,image_folder,fold
0,1.2.826.0.1.3680043.1363,1,0,0,0,0,1,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,0
1,1.2.826.0.1.3680043.25704,0,0,0,0,0,0,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,0
2,1.2.826.0.1.3680043.20647,0,0,0,0,0,0,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,0
3,1.2.826.0.1.3680043.31077,1,0,0,1,1,1,1,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,0
4,1.2.826.0.1.3680043.17960,0,0,0,0,0,0,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,0
...,...,...,...,...,...,...,...,...,...,...,...,...
82,1.2.826.0.1.3680043.32071,1,0,1,0,1,0,1,1,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,4
83,1.2.826.0.1.3680043.30524,1,0,0,0,0,0,1,1,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,4
84,1.2.826.0.1.3680043.28025,0,0,0,0,0,0,0,0,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,4
85,1.2.826.0.1.3680043.21321,1,1,1,1,0,0,0,1,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,4
86,1.2.826.0.1.3680043.26990,1,0,0,0,0,1,1,1,/Volumes/Data/kaggle/raw/segmentations/1.2.826...,/Volumes/Data/kaggle/raw/train_images/1.2.826....,4